Added license solver
thoth-station/storages pull request #2634
Opened 2022-05-06 10:43 UTC by meile18

## TODO

- [ ] set thoth-license-solver >= 0.1.4

## This introduces a breaking change

- [x] No

## This should yield a new module release

- [x] Yes

## This Pull Request implements

Added license-solver:
- new table `python_package_license`
- new columns in `python_package_version`:
  - package_license
  - package_license_warning

2022-05-06 12:48 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **fridex** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fstorages).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/storages/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["fridex"]} -->

2022-05-06 13:03 UTC, sesheta commented
@meile18: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 1fe334199f4d67ed23ef2ce2855168ca836a011b | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_storages/2634/pre-commit/1522558937004511232) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=storages&pr=2634). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Ameile18). Please help us and [open an issue](https://github.com/thoth-station/storages/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-05-06 16:35 UTC, harshad16 requested changes
thanks for pr
i have drop some comment

2022-05-06 16:35 UTC, harshad16 commented on thoth/storages/graph/postgres.py
> +# from .models import PythonPackageLicense
Seems like these are mistakenly commented
can please uncomment it.

2022-05-06 16:35 UTC, harshad16 commented on thoth/storages/graph/postgres.py
> +from thoth.license_solver import detect_license
This is not needed here , right
as this is already used in solver, and we would directly insert the result of solver via sync.

2022-05-06 16:35 UTC, harshad16 commented on thoth/storages/graph/postgres.py
> +                # package_license = python_package_info["package_license"]
same here

2022-05-06 16:35 UTC, harshad16 commented on thoth/storages/graph/postgres.py
> +                # )
license_version and license_identifier are also needed by the methid

2022-05-12 10:24 UTC, meile18 commented
hi @harshad16, my bad I didn't write in the description that I was solving an error with @fridex. For now, it's code for "debugging". I will update you about the code review.

2022-05-12 10:39 UTC, sesheta commented
@meile18: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 8dec4a6e9c73dafde9b1c22700a3012133073cd3 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_storages/2634/pre-commit/1524697516057038848) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=storages&pr=2634). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Ameile18). Please help us and [open an issue](https://github.com/thoth-station/storages/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-06-09 07:28 UTC, closed without merging